version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - NODE_ENV=production
      - ASSET_HUB_URL=ws://host.docker.internal:63170
      - RELAY_CHAIN_URL=ws://host.docker.internal:63168
      - PORT=8080
      - LOG_LEVEL=info
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped 
